In [98]:
import numpy as np
a=np.array([20,30,40])
b=np.array([60,70,80])
print(a+b)

[ 80 100 120]


In [99]:
a = np.array(["78","30",78])
print(a)

['78' '30' '78']


In [100]:
l1 =[20,30,40]
l2 =[50,60,70]
print(l1+l2)

[20, 30, 40, 50, 60, 70]


In [101]:
import numpy as np

In [102]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr)
print(type(arr))

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>


In [103]:
arr1=np.array([10,20,30,40])
print(arr1[::-1])
print(len(arr1))

[40 30 20 10]
4


In [104]:
arr1=np.array([[10,20,30,40],[50,60,70,80]])
print(arr1[::-1,::-1])
print(len(arr1))

[[80 70 60 50]
 [40 30 20 10]]
2


In [105]:
arr1=np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
#print(arr1[0:2,0:2])  both array slicing
#print(arr1[0,1:3])    0 index frist array
#print(arr1[1,0:4])     1 index second array
#print(arr1[2,0:3])      2 index second array

#print(np.shape(arr1))   no. of rows and column
#print(np.size(arr1))     no. of element
print(np.ndim(arr1))    # array dimensions
print(arr.dtype)        # datatype of array
print(len(arr1))        # no. of nested values
print(arr1.astype(str))  # conversion of datatype

2
int64
3
[['10' '20' '30' '40']
 ['50' '60' '70' '80']
 ['20' '40' '60' '80']]


In [106]:
import numpy as np
a = [[30,40,40],[40,30,10]]
arr = np.array(a)
print(arr)
print(arr.shape)  
print(arr.size)
print(len(arr))   
print(type(arr))
print(arr.dtype)
print(arr.astype(str))

[[30 40 40]
 [40 30 10]]
(2, 3)
6
2
<class 'numpy.ndarray'>
int64
[['30' '40' '40']
 ['40' '30' '10']]


In [107]:
import numpy as np 
arr1=np.array([30,30,40,50,60])
arr2=np.array([30,40,50,60,70])
print(arr1+arr2)
print(np.add(arr1,arr2))

[ 60  70  90 110 130]
[ 60  70  90 110 130]


In [108]:
import numpy as np 
arr1=np.array([[30,40],[50,60]])
arr2=np.array([[30,40],[60,70]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))


[[  0   0]
 [-10 -10]]
[[  0   0]
 [-10 -10]]


In [109]:
import numpy as np 
arr1=np.array([[30,40],[50,60]])
arr2=np.array([[30,40],[60,70]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[ 900 1600]
 [3000 4200]]
[[ 900 1600]
 [3000 4200]]


In [110]:
import numpy as np 
arr1=np.array([[30,40],[50,60]])
arr2=np.array([[30,40],[60,70]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[1.         1.        ]
 [0.83333333 0.85714286]]
[[1.         1.        ]
 [0.83333333 0.85714286]]


In [111]:
import numpy as np 
arr1=np.array([3,4,5,6])
arr2=np.array([2])
print(np.power(arr1,arr2))

[ 9 16 25 36]


In [112]:
import numpy as np 
arr1=np.array([9,16,35,36])
print(np.sqrt(arr1))
print(arr1.astype(int))
 

[3.         4.         5.91607978 6.        ]
[ 9 16 35 36]


In [113]:
import numpy as np 
arr1=np.array([9,16,35,36])
a=np.sqrt(arr1)
print(a.astype(int))

[3 4 5 6]


In [114]:
#Concatenate
import numpy as np
arr1 = np.array([30,40,50])
arr2 = np.array([4,5,6])
print(np.concatenate([arr1,arr2]))

[30 40 50  4  5  6]


In [115]:
#Concatenate
import numpy as np
arr1 = np.array([[30,40],[50,50]])
arr2 = np.array([[4,5],[6,8]])
print(np.concatenate([arr1,arr2]))


[[30 40]
 [50 50]
 [ 4  5]
 [ 6  8]]


In [116]:
print(np.concatenate([arr1,arr2],axis = 1))

[[30 40  4  5]
 [50 50  6  8]]


In [117]:
print(np.hstack([arr1,arr2])) #horizontal concatination

[[30 40  4  5]
 [50 50  6  8]]


In [118]:
print(np.vstack([arr1,arr2])) #vertical concatination

[[30 40]
 [50 50]
 [ 4  5]
 [ 6  8]]


In [119]:
a = np.array([20,30,40,50,10,20]) #splict means divinded array into part
print(np.array_split(a,4))

[array([20, 30]), array([40, 50]), array([10]), array([20])]


In [120]:
a = np.array([[20,30,40],[50,10,20]]) #splict means divinded 2D array into part
print(np.array_split(a,4))

[array([[20, 30, 40]]), array([[50, 10, 20]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]


In [121]:
import numpy as np
a =np.array([20,40,60,80])
print(np.append(a,90))

[20 40 60 80 90]


In [122]:
import numpy as np
a =np.array([[20,40],[60,80]])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [123]:
import numpy as np
a =np.array([20,40,60,80])
print(np.append(a,90))
print(np.insert(a,1,10))     #array , index , value

[20 40 60 80 90]
[20 10 40 60 80]


In [124]:
import numpy as np
a =np.array([[20,40],[60,80]])
print(np.append(a,[90,100]))
print(np.insert(a,1,[10,70], axis = 1))     #array , index , value
print(np.insert(a,1,[10,70], axis = 0)) 

[ 20  40  60  80  90 100]
[[20 10 40]
 [60 70 80]]
[[20 40]
 [10 70]
 [60 80]]


In [125]:
print(np.delete(a,1))  # axis = 1 rows baise axis = 0 column baise

[20 60 80]


Sort filter and search

In [126]:
import numpy as np
a = np.array([[7,8,4,12,9],[2,8,5,1,3]])
print(np.sort(a))

[[ 4  7  8  9 12]
 [ 1  2  3  5  8]]


In [127]:
a = np.array([3,4,1,7,8])
s = np.where(a == 4 )
print(s)

(array([1]),)


In [128]:
a = np.array([1,2,3,4,5])
s = np.searchsorted(a,3)
print(s)

2


In [129]:
a = np.array([20,30,40,50])
f = [True,False,True,False]
n = a[f]
print(n)

[20 40]


In [130]:
a = np.array([20,30,40,50])
f = a>=30
n = a[f]
print(n)

[30 40 50]


In [131]:
import numpy as np
a = np.array([20,40,60,70])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.median(a))
print(np.cumsum(a))
print(np.cumprod(a))

190
20
70
4
47.5
50.0
[ 20  60 120 190]
[     20     800   48000 3360000]


In [132]:
a =[100,150,199,200,250,130]
b=[10,50,30,40,30,10]
price=np.array(a)
quantity=np.array(b)
print(price,"\n",quantity)

c=(np.cumprod([price,quantity],axis = 0))
print(c)
print(c[1].sum())


[100 150 199 200 250 130] 
 [10 50 30 40 30 10]
[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]
31270


In [133]:
import numpy as np
import statistics as st
baked_food=[200,150,150,130,200,220,170,188] 
a = np.array(baked_food)
print(np.sort(a))
print(np.mean(a))   #sum of all the value/num of  the value
print(np.median(a))  
print(st.mode(a))
print(np.std(a))
print(np.var(a)) 

[130 150 150 170 188 200 200 220]
176.0
179.0
200
29.017236257093817
842.0


Cofficent of co-relation check dependence on data

In [ ]:
import numpy as np
tobacco_consumption =np.array([30,50,10,30,50,40])
deaths =np.array([100,120,70,100,120,112])
print(np.corrcoef([tobacco_consumption,deaths])) # -1 is strong relation and +1 is weak relation and 0 means neutral

[[1.         0.99015454]
 [0.99015454 1.        ]]
